name: Build

on:
  push:
    branches: [PYTHON_3.10]
  pull_request:
    branches: [PYTHON_3.10]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build
        run: bash build.sh
